[package]
name = "diagram-symbols-shapes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Generic shape symbol plugin for diagram (rectangle, circle, oval, explosion, arrow)."

[dependencies]
diagram-core.workspace = true
