[package]
name = "drawskill-symbols-schematic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Schematic (electronic) symbol plugin for drawskill."

[dependencies]
drawskill-core.workspace = true
